import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:udemy_grocery_app/data/categories.dart';
import 'package:udemy_grocery_app/models/grocery_item.dart';
import 'package:udemy_grocery_app/widgets/new_item.dart';
import 'package:http/http.dart' as http;

class GroceryList extends StatefulWidget {
  const GroceryList({super.key});

  @override
  State<GroceryList> createState() => _GroceryListState();
}

class _GroceryListState extends State<GroceryList> {
  //empty list
  List<GroceryItem> _groceryItems = [];

  var isLoading = true;

  String? _error;

  //if state object is created for the first time
  //initState ensures loaditems is kicked in or triggered

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _loadItems();
  }

  void _loadItems() async {
    final url = Uri.https(
      "groceryapp-4ea49-default-rtdb.firebaseio.com",
      'shopping-list.json',
    );

    try{
      final response = await http.get(url);

      if (response.statusCode >= 400) {
        setState(() {
          _error = "Failed to fetch data, please try again later";
        });
      }

      //firebase returns string null

      if (response.statusCode =="null") {
        setState(() {
          isLoading=false;
        });
        return;
      }

//if null then rest of code is not executed


      final Map<String, dynamic> listData = jsonDecode(response.body);

      final List<GroceryItem> _loadedItems = [];
      for (final item in listData.entries) {
        //searches for something in a list that matches the first search in the entries
        //ie received value is searched across the categories data list
        //returns a bool;
        final category =
            categories.entries
                .firstWhere(
                  (catItem) => catItem.value.title == item.value['category'],
            )
                .value;

        //for every response we recieve we create a groceryItem
        _loadedItems.add(
          GroceryItem(
            //id generated by firebase
            id: item.key,
            name: item.value["name"],
            quantity: item.value["quantity"],
            category: category,
          ),
        );
      }

      //overwrite the list
      setState(() {
        _groceryItems = _loadedItems;
        isLoading = false;
      });


    }
    catch(error){
      setState(() {
        _error = "Failed to fetch data, please try again later";
      });
    }


     }

  void _addItem() async {
    final newItem = await Navigator.of(
      context,
    ).push<GroceryItem>(MaterialPageRoute(builder: (context) => NewItem()));

    if (newItem == null) {
      return;
    }

    setState(() {
      _groceryItems.add(newItem);
    });
  }

  void _removeItem(GroceryItem item) async {
    final index = _groceryItems.indexOf(item);

    setState(() {
      _groceryItems.remove(item);
    });

    // / is used to navigate the folders by the injected ID
    final url = Uri.https(
      "groceryapp-4ea49-default-rtdb.firebaseio.com",
      'shopping-list/${item.id}.json',
    );

    final response = await http.delete(url);

    //inserts the element if its not deleted from the backend
    if (response.statusCode >= 400) {
      setState(() {
        _groceryItems.insert(index, item);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    Widget content = Center(
      child: const Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Icon(Icons.add, size: 60, color: Colors.white),
          SizedBox(height: 8),
          Text(
            "There's nothing here, lets add some",
            style: TextStyle(
              fontWeight: FontWeight.bold,
              fontSize: 16,
              color: Colors.white,
            ),
          ),
        ],
      ),
    );

    if (isLoading) {
      content = Center(child: CircularProgressIndicator());
    }

    if (_groceryItems.isNotEmpty) {
      content = ListView.builder(
        //flutter knows how often to call
        itemCount: _groceryItems.length,
        //arguments is automatically passed in by flutter
        itemBuilder:
            (ctx, index) => Dismissible(
              key: ValueKey(_groceryItems[index].id),
              onDismissed: (direction) {
                _removeItem(_groceryItems[index]);
              },
              child: ListTile(
                leading: Container(
                  width: 24,
                  height: 24,
                  //color of every category based on index
                  color: _groceryItems[index].category.color,
                ),
                title: Text(_groceryItems[index].name),
                //output quantity
                trailing: Text(_groceryItems[index].quantity.toString()),
              ),
            ),
      );
    }

    //if we have an error
    if (_error != null) {
      content = Center(child: Text(_error!));
    }

    return Scaffold(
      appBar: AppBar(
        title: Text("Your Groceries"),
        actions: [
          ElevatedButton.icon(
            icon: Icon(Icons.add),
            onPressed: _addItem,
            label: Text('Add'),
          ),
        ],
      ),
      body: content,
    );
  }
}
